version: "3"
networks:
    http3:
services:
    webbclient:
        build:
            context: ./webbclient/
            dockerfile: Dockerfile
        container_name: "webbclient"
        ports:
            - "1337:1337"
        networks:
            http3:

    db:
        image: mysql
        restart: always
        container_name: "database"
        environment:
            MYSQL_ROOT_PASSWORD: vteam
            MYSQL_DATABASE: Elsparkcyklar
            MYSQL_USER: vteam
            MYSQL_PASSWORD: vteam
        ports:
            - "3306:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
