name: Unit Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Navigate to subfolder
        run: cd api/
      - name: Install in subfolder
        run: npm i
      - name: Navigate back to main directory
        run: cd ..
      - name: tests
        run: npm test
